version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ec2-user/asmo
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
