server:
  port: 48888

spring:
  profiles:
    group:
      local:
        - common
        - local-mysql
      prod:
        - common
        - prod-aws
        - prod-mysql


---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  level:
    org.springframework.web.filter: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSSz,UTC
#app:
#  token:
#    secretKey: asmo_secret_key
#    accessTokenExpireSeconds: 3600000
#    refreshTokenexpireSeconds: 3600000
#    prefix: Bearer

---
spring:
  config:
    activate:
      on-profile: local-mysql
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:43306/asmo
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: prod-aws
    import: aws-parameterstore:/config/asmo/
---
spring:
  config:
    activate:
      on-profile: prod-mysql
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USR}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: false
